Added stubs for `exempt` commands, change serialization of `Student`
Tests fail due to `seedu.address.testutil.TypicalStudents` not being initialized.
This bug will be investigated and fixed in a later commit.

```
Could not initialize class seedu.address.testutil.TypicalStudents
java.lang.NoClassDefFoundError: Could not initialize class seedu.address.testutil.TypicalStudents
	at seedu.address.model.ModelManagerTest.hasStudent_studentNotInPlanner_returnsFalse(ModelManagerTest.java:81)
```